---
pagetitle: "TITLE GOES HERE"
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(
  fig.width=8,
  fig.align="center",
  fig.asp=0.618,
  out.width="100%",
  echo=FALSE,
  comment=""
)

suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(lubridate))
suppressPackageStartupMessages(library(scales))

theme_set(
  theme_bw() +
  theme(
    panel.grid.minor=element_blank()
  )
)

```

```{r loading-data, message=FALSE}

# filename = commandArgs(TRUE) # a vector
# filename = list.files(pattern="*.tsv") |> max()
filename = "..."

# -------------------------------------------------

# temporary: upgrade to next block
d <- read_tsv(filename, col_names=c("...", "..."))
d |> spec()
d |> spec() |> cols_condense()

# -------------------------------------------------

d <- read_tsv(filename,
       col_names=c("...", "..."),
       col_types=cols(
         "..." = col_datetime(),
         "..." = col_character(),
         "..." = col_factor(),
         "..." = col_number(),
     ))

# -------------------------------------------------

ggplot(d, aes(...)) +
  geom_point(alpha=0.3, color="darkgreen", stroke=0, size=2.5) +
  scale_y_continuous(labels=comma) +
  NULL

```

